#!/bin/bash

# SOBIE 2023 Program Parser - Updated Command
# File moved from: /uploads/documents/2019/program/sobie-2023-program.pdf
# File now at: /uploads/documents/2023/program/sobie-2023-program.pdf

echo "📄 SOBIE 2023 Program Parser - Updated File Path"
echo "=============================================="
echo ""
echo "✅ PDF Location Verified:"
echo "   /Users/bcumbie/Desktop/sobie-dev/sobieNode/uploads/documents/2023/program/sobie-2023-program.pdf"
echo ""
echo "📋 Updated Parse Command:"
echo ""
echo "curl -X POST \"http://localhost:3000/api/admin/parse-program\" \\"
echo "  -H \"Authorization: Bearer <admin_token>\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"filePath\": \"/Users/bcumbie/Desktop/sobie-dev/sobieNode/uploads/documents/2023/program/sobie-2023-program.pdf\","
echo "    \"year\": 2023"
echo "  }'"
echo ""
echo "🔐 To get admin token, first register/login as admin:"
echo ""
echo "# Register admin user:"
echo "curl -X POST \"http://localhost:3000/api/auth/register\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"name\": { \"first\": \"Admin\", \"last\": \"User\" },"
echo "    \"email\": \"admin@sobie.org\","
echo "    \"password\": \"AdminPassword123!\","
echo "    \"role\": \"admin\""
echo "  }'"
echo ""
echo "# Then login to get token:"
echo "curl -X POST \"http://localhost:3000/api/auth/login\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"email\": \"admin@sobie.org\","
echo "    \"password\": \"AdminPassword123!\""
echo "  }'"
echo ""
echo "📊 This will extract and populate:"
echo "  - Conference information for SOBIE 2023"
echo "  - Attendee profiles and affiliations"
echo "  - Presentation and research data"
echo "  - Session and schedule information"
echo "  - Committee and sponsor details"
echo "  - Historical database records"
